import { z } from 'zod';

const passwordSchema = z
  .string()
  .min(8, 'Password must be at least 8 characters')
  .max(32, 'Password must not exceed 32 characters')
  .regex(/[A-Z]/, 'Password must contain at least one uppercase letter')
  .regex(/[a-z]/, 'Password must contain at least one lowercase letter')
  .regex(/[0-9]/, 'Password must contain at least one number')
  .regex(
    /[@$!%*?&]/,
    'Password must contain at least one special character (@$!%*?&)'
  );

const userSchema = z
  .object({
    id: z.string().uuid(), // Generated by Prisma
    username: z
      .string()
      .trim()
      .min(3, 'Username must be at least 3 characters'),
    firstName: z.string().trim(),
    lastName: z.string().trim(),
    email: z.string().email(),
    password: passwordSchema.optional().nullable(),
    googleId: z.string().optional().nullable(),
    role: z.enum(['USER', 'ADMIN']).default('USER'),
    isVerified: z.boolean().default(false), // Added isVerified field
    verifyToken: z.string().optional().nullable(), // Verification token if needed
    createdAt: z.date().optional(), // Generated by Prisma
    orders: z.any().optional(), // Not needed for creation
    reviews: z.any().optional(), // Not needed for creation
  })
  .refine(
    (data) => data.password !== undefined || data.googleId !== undefined,
    {
      message: 'Either password or Google ID must be provided',
      path: ['password'],
    }
  );

const productsSchema = z.object({
  name: z.string().trim().min(3).max(50),
  description: z.string().optional().default(''), // Allow empty description
  price: z.number().positive('Price must be positive').default(0),
  stock: z.number().int().nonnegative('Stock must be 0 or more').default(0),
  imageUrl: z.string().url('Invalid image URL'), // Ensure it's a valid URL
});

const loginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(8),
});

const reviewsSchema = z.object({
  userId: z.string().uuid(),
  productId: z.string().uuid(),
  rating: z.number().positive().max(5).default(0),
  comment: z.string().default(''),
});

const cartSchema = z.object({
  productId: z.string().uuid(),
  price: z.number().positive('Price must be positive').default(0.0),
  quantity: z.number().positive('quantity must be positive').default(1),
});

export type User = z.infer<typeof userSchema>;
export type Product = z.infer<typeof productsSchema>;
export type Login = z.infer<typeof loginSchema>;
export type reviews = z.infer<typeof reviewsSchema>;
export type Cart = z.infer<typeof cartSchema>;

export {
  passwordSchema,
  userSchema,
  productsSchema,
  loginSchema,
  reviewsSchema,
  cartSchema,
};
